# Generated by Django 3.0.2 on 2021-10-14 18:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('planetly_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 14, 18, 9, 0, 197267, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
