# Generated by Django 3.0.2 on 2021-10-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planetly_app', '0004_auto_20211014_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'UserProfile', 'verbose_name_plural': 'UsersProfiles'},
        ),
        migrations.AlterField(
            model_name='usage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planetly_app.Profile'),
        ),
    ]
